import { highlight } from '@/lib/shiki'

// Hardcoded integration snippet — safe for dangerouslySetInnerHTML (T-08-01 accepted).
// This is a constant, never user input.
const CODE = `import { UploadButton } from "@uploadkitdev/react"

export default function Page() {
  return <UploadButton endpoint="imageUploader" />
}`

export default async function HeroCode() {
  const html = await highlight(CODE, 'tsx')

  return (
    <div
      className="hero-code relative overflow-hidden rounded-[var(--radius-lg)]"
      style={{
        background: 'var(--color-surface-elevated)',
        border: '1px solid var(--color-surface-border)',
        boxShadow: '0 24px 80px -20px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.04)',
      }}
      aria-label="UploadKit integration code example"
    >
      {/* Window chrome bar — decorative, aria-hidden */}
      <div
        className="flex items-center gap-2 border-b px-4 py-3"
        style={{ borderColor: 'var(--color-surface-border)' }}
        aria-hidden="true"
      >
        <span className="h-3 w-3 rounded-full bg-[#ff5f57]" />
        <span className="h-3 w-3 rounded-full bg-[#febc2e]" />
        <span className="h-3 w-3 rounded-full bg-[#28c840]" />
        <span
          className="ml-auto font-mono text-xs"
          style={{ color: 'var(--color-text-secondary)' }}
        >
          page.tsx
        </span>
      </div>

      {/* Syntax-highlighted code block — line-by-line reveal animation via CSS */}
      <div
        className="p-5"
        // Safe: html comes from highlight() which processes a hardcoded constant
        dangerouslySetInnerHTML={{ __html: wrapLines(html) }}
      />
    </div>
  )
}

/**
 * Wraps each line of Shiki's output in a <span class="code-line"> for
 * the CSS stagger-reveal animation. Works by splitting on newlines inside
 * the <code> element generated by Shiki.
 *
 * Shiki emits: <pre class="shiki ..."><code>...line1\nline2\n...</code></pre>
 * We replace the inner code content with wrapped spans.
 */
function wrapLines(shikiHtml: string): string {
  // Extract content between <code> and </code>
  const match = shikiHtml.match(/<code>([\s\S]*?)<\/code>/)
  if (!match) return shikiHtml

  const codeContent = match[1] ?? ''
  // Split on literal newlines (not inside tags) — Shiki uses \n between lines
  const lines = codeContent.split('\n')
  // Remove trailing empty line Shiki often adds
  const trimmedLines = lines[lines.length - 1] === '' ? lines.slice(0, -1) : lines

  const wrappedLines = trimmedLines
    .map((line) => `<span class="code-line">${line}</span>`)
    .join('\n')

  return shikiHtml.replace(/<code>[\s\S]*?<\/code>/, `<code>${wrappedLines}</code>`)
}
