// @ts-nocheck
import * as __fd_glob_76 from "../content/docs/sdk/react/use-uploadkit.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/sdk/react/upload-step-wizard.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/sdk/react/upload-progress-stacked.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/sdk/react/upload-progress-radial.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/sdk/react/upload-progress-orbit.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/sdk/react/upload-progress-bar.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/sdk/react/upload-particles.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/sdk/react/upload-modal.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/sdk/react/upload-inline-chat.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/sdk/react/upload-dropzone.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/sdk/react/upload-dropzone-terminal.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/sdk/react/upload-dropzone-glass.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/sdk/react/upload-dropzone-brutal.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/sdk/react/upload-dropzone-aurora.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/sdk/react/upload-cloud-rain.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/sdk/react/upload-button.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/sdk/react/upload-button-shimmer.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/sdk/react/upload-button-magnetic.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/sdk/react/upload-bento.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/sdk/react/upload-avatar.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/sdk/react/theming.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/sdk/react/progress.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/sdk/react/installation.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/sdk/react/file-preview.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/sdk/react/file-list.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/sdk/react/config-mode.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/sdk/react/before-upload.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/sdk/react/api-reference.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/sdk/next/type-safety.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/sdk/next/ssr-plugin.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/sdk/next/middleware.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/sdk/next/installation.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/sdk/next/file-router.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/sdk/next/backend-adapters.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/sdk/next/api-reference.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/sdk/core/upload.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/sdk/core/installation.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/sdk/core/delete.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/sdk/core/configuration.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/sdk/core/api-reference.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/guides/multipart-upload.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/guides/migration-from-uploadthing.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/guides/image-upload.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/guides/document-upload.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/guides/custom-styling.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/guides/avatar-upload.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/getting-started/react.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/getting-started/nextjs.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/getting-started/api-only.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/dashboard/projects.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/dashboard/overview.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/dashboard/files.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/dashboard/billing.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/dashboard/api-keys.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/core-concepts/security.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/core-concepts/presigned-urls.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/core-concepts/file-routes.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/core-concepts/byos.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/api-reference/webhooks.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/api-reference/upload.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api-reference/rest-api.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api-reference/projects.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/api-reference/files.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/api-reference/errors.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/api-reference/authentication.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/sdk/react/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/sdk/next/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/sdk/core/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/sdk/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/core-concepts/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/dashboard/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api-reference/meta.json": __fd_glob_1, "guides/meta.json": __fd_glob_2, "dashboard/meta.json": __fd_glob_3, "core-concepts/meta.json": __fd_glob_4, "getting-started/meta.json": __fd_glob_5, "sdk/meta.json": __fd_glob_6, "sdk/core/meta.json": __fd_glob_7, "sdk/next/meta.json": __fd_glob_8, "sdk/react/meta.json": __fd_glob_9, }, {"index.mdx": __fd_glob_10, "api-reference/authentication.mdx": __fd_glob_11, "api-reference/errors.mdx": __fd_glob_12, "api-reference/files.mdx": __fd_glob_13, "api-reference/projects.mdx": __fd_glob_14, "api-reference/rest-api.mdx": __fd_glob_15, "api-reference/upload.mdx": __fd_glob_16, "api-reference/webhooks.mdx": __fd_glob_17, "core-concepts/byos.mdx": __fd_glob_18, "core-concepts/file-routes.mdx": __fd_glob_19, "core-concepts/presigned-urls.mdx": __fd_glob_20, "core-concepts/security.mdx": __fd_glob_21, "dashboard/api-keys.mdx": __fd_glob_22, "dashboard/billing.mdx": __fd_glob_23, "dashboard/files.mdx": __fd_glob_24, "dashboard/overview.mdx": __fd_glob_25, "dashboard/projects.mdx": __fd_glob_26, "getting-started/api-only.mdx": __fd_glob_27, "getting-started/nextjs.mdx": __fd_glob_28, "getting-started/quickstart.mdx": __fd_glob_29, "getting-started/react.mdx": __fd_glob_30, "guides/avatar-upload.mdx": __fd_glob_31, "guides/custom-styling.mdx": __fd_glob_32, "guides/document-upload.mdx": __fd_glob_33, "guides/image-upload.mdx": __fd_glob_34, "guides/migration-from-uploadthing.mdx": __fd_glob_35, "guides/multipart-upload.mdx": __fd_glob_36, "sdk/core/api-reference.mdx": __fd_glob_37, "sdk/core/configuration.mdx": __fd_glob_38, "sdk/core/delete.mdx": __fd_glob_39, "sdk/core/installation.mdx": __fd_glob_40, "sdk/core/upload.mdx": __fd_glob_41, "sdk/next/api-reference.mdx": __fd_glob_42, "sdk/next/backend-adapters.mdx": __fd_glob_43, "sdk/next/file-router.mdx": __fd_glob_44, "sdk/next/installation.mdx": __fd_glob_45, "sdk/next/middleware.mdx": __fd_glob_46, "sdk/next/ssr-plugin.mdx": __fd_glob_47, "sdk/next/type-safety.mdx": __fd_glob_48, "sdk/react/api-reference.mdx": __fd_glob_49, "sdk/react/before-upload.mdx": __fd_glob_50, "sdk/react/config-mode.mdx": __fd_glob_51, "sdk/react/file-list.mdx": __fd_glob_52, "sdk/react/file-preview.mdx": __fd_glob_53, "sdk/react/installation.mdx": __fd_glob_54, "sdk/react/progress.mdx": __fd_glob_55, "sdk/react/theming.mdx": __fd_glob_56, "sdk/react/upload-avatar.mdx": __fd_glob_57, "sdk/react/upload-bento.mdx": __fd_glob_58, "sdk/react/upload-button-magnetic.mdx": __fd_glob_59, "sdk/react/upload-button-shimmer.mdx": __fd_glob_60, "sdk/react/upload-button.mdx": __fd_glob_61, "sdk/react/upload-cloud-rain.mdx": __fd_glob_62, "sdk/react/upload-dropzone-aurora.mdx": __fd_glob_63, "sdk/react/upload-dropzone-brutal.mdx": __fd_glob_64, "sdk/react/upload-dropzone-glass.mdx": __fd_glob_65, "sdk/react/upload-dropzone-terminal.mdx": __fd_glob_66, "sdk/react/upload-dropzone.mdx": __fd_glob_67, "sdk/react/upload-inline-chat.mdx": __fd_glob_68, "sdk/react/upload-modal.mdx": __fd_glob_69, "sdk/react/upload-particles.mdx": __fd_glob_70, "sdk/react/upload-progress-bar.mdx": __fd_glob_71, "sdk/react/upload-progress-orbit.mdx": __fd_glob_72, "sdk/react/upload-progress-radial.mdx": __fd_glob_73, "sdk/react/upload-progress-stacked.mdx": __fd_glob_74, "sdk/react/upload-step-wizard.mdx": __fd_glob_75, "sdk/react/use-uploadkit.mdx": __fd_glob_76, });